[project]
name = "microformats-parser-website"
version = "1.0.0"
description = "A web interface for parsing microformats using mf2py"
readme = "README.md"
license = "CC0-1.0"
requires-python = "==3.14.2"
dependencies = [
    "flask==2.2.2",
    "gunicorn==20.1.0",
    "mf2py==1.1.2",
    "mf2util==0.5.1",
]
